// Labels - used in buttons, forms and such
export const LABELS = {
    COMMON: {
        ABORT: "Avbryt",
        ADD: "Lägg till",
        ADMIN: "Admin",
        ADD_ADMIN_1: "Gör ",
        ADD_ADMIN_2: " till admin",
        BACK: "Tillbaka",
        BACK_TO: "Tillbaka till",
        BACK_TO_TOP: "Tillbaka till toppen",
        BREADCRUMB: "Brödsmula",
        CHOOSE: "--- Välj ---",
        CLOSE: "Stäng",
        CONTACT: "Kontakt",
        MORE_CONTENT: "Innehåll",
        CREATE_ACCOUNT: "Registrera dig",
        CREATED_AT: "Inlagd",
        DATE: "Datum",
        DELETE: "Ta bort",
        DELETE_IMAGE: "Ta bort bild",
        DELETING: "Tar bort",
        DESCRIPTION_DB: "Beskrivning (description)",
        DO_FILTER: "Filtrera",
        EDIT: "Redigera",
        EDIT_INFORMATION: "Redigera information",
        EMAIL: "E-postadress",
        GO_TO: "Gå till",
        HOME: "Hem",
        ID: "Id",
        IMAGE: "Bild",
        INFORMATION: "Information",
        LINKS: "Länkar",
        LIST_VIEW_GRADE_VALUE_HIDE: "Dölj skickvärdering",
        LIST_VIEW_GRADE_VALUE_SHOW: "Visa skickvärdering",
        LIST_VIEW_GRID_SHOW: "Visa som grid",
        LIST_VIEW_LIST_SHOW: "Visa som lista",
        LATEST_LOG_IN: "Senast inloggad:",
        LOG_IN: "Logga in",
        NAME_DB: "Namn (name)",
        NEXT: "Nästa",
        NUMBER_DB: "Nummer (number)",
        PAUSE: "Pausa",
        REMOVE: "Ta bort",
        RESET: "Rensa",
        RESET_FILTER: "Rensa alla filter",
        RESET_FORM: "Rensa formulär",
        RESET_PASSWORD: "Ändra lösenord",
        SAVE: "Spara",
        SEARCH: "Sök",
        SEND: "Skicka",
        SETTINGS: "Inställningar",
        SETTINGS_CREDENTIALS: "Inloggningsuppgifter",
        SHOW_MORE: "Visa mer",
        SHOW_LESS: "Visa mindre",
        WEBSITE: "Webbplats",
        WIKI_URL_DB: "Länk till Seriewikin (wiki_url)",
        YEAR_DB: "År (year)"
    },
    SECTIONS: {
        DASHBOARD: {
            NAME: "Kontrollpanel",
            LINKS: {
                MY_TITLES: "Kontrollpanel / Mina titlar"
            },
            OVERVIEW: {
                INCOMING_MESSAGES: "Inkomna meddelanden",
                USEFUL_LINKS: "Nyttiga länkar"
            }
        },
        GRADES: {
            GRADE: "Skickgradering",
            ADD_GRADE: "Lägg till skickgradering",
            GRADE_VALUE: "Skickvärdering",
            GRADE_VALUES: "Skickvärderingar",
            GRADE_VALUES_FOR: "Skickvärdering för",
            ADD_GRADE_VALUE_VALUES: "Lägg till skickvärden för publikationerna",
            EDIT_GRADE_VALUE_VALUES: "Redigera skickvärden",
        },
        ISSUES: {
            ALL_ISSUES: "Alla publikationer",
            IS_DOUBLE_DB: "Dubbelnummer (is_double)",
            IS_VARIANT_DB: "Variant (is_variant) - Används även för undertitel",
            ISSUES: "Publikationer",
            VARIANT_SUFFIX_DB: "Variant suffix (variant_suffix)",
            UPGRADE_ISSUES: "Publikationer i behov av uppgradering",
            NO_UPGRADE_ISSUES: "Du har inga publikationer i behov av uppgradering."
        },
        MARVELKLUBBEN: {
            IS_MARVELKLUBBEN_DB: "Ingår i marvelklubben (is_marvelklubben)",
            MARVELKLUBBEN: "Marvelklubben",
            MARVELKLUBBEN_NUMBER_DB: "Marvelklubben nummer (marvelklubben_number)",
        },
        MESSAGES: {
            ALL_MESSAGES: "Alla meddelanden",
            MESSAGE: "Meddelande",
            MESSAGES: "Meddelanden",
            MESSAGE_CLOSE: "Stäng meddelande",
            MESSAGE_SHOW: "Meddelande",
            MESSAGE_TITLE: "Rubrik",
        },
        PUBLISHERS: {
            ADD_PUBLISHER: "Lägg till förlag",
            ALL_PUBLISHERS: "Alla förlag",
            COUNTRY_DB: "Utgivningsland (country)"
        },
        TITLES: {
            ADD_TITLE: "Lägg till titel",
            ALL_TITLES: "Alla titlar",
            COMICS_ORG_URL_DB: "Länk till Comics.org (comics_org_url)",
            END_YEAR_DB: "Slutår (end_year)",
            FORMAT_DB: "Format (format)"
        },
        USERS: {
            ALL_USERS: "Alla användare",
            ALLOW_LOCATION_ACCESS: "Tillåt platsåtkomst",
            FIRST_NAME: "Förnamn",
            IS_PUBLIC: "Publik information",
            IS_SUPER_ADMIN: " är super admin.",
            LAST_NAME: "Efternamn",
            MY_WEBSITE: "Min hemsida",
            REMOVE_ADMIN_1: "Ta bort ",
            REMOVE_ADMIN_2: " som admin",
        }
    }
}

export const BREADCRUMB_NAMES = {
    ADD: "Lägg till",
    ADMIN: "Admin",
    DASHBOARD: "Kontrollpanel",
    EDIT: "Redigera",
    GRADE_VALUES: "Skickvärderingar",
    HOME: "Hem",
    ISSUES: "Publikationer",
    MARVELKLUBBEN: "Marvelklubben",
    MESSAGES: "Meddelanden",
    MY_TITLES: "Mina titlar",
    COLLECTIONS: "Samlingar",
    MAPS: "Karta",
    OVERVIEW: "Översikt",
    PROFILE: "Inställningar",
    PUBLISHERS: "Alla förlag",
    TITLES: "Alla titlar",
    USERS: "Alla användare",
    VALUATION: "Värdering",
}