// Texts - for longer text blocks
export const TEXTS = {
    ADD_ISSUE_FOR: "Lägg till enstaka publikation för",
    ADD_ISSUE_WANTED: "Efterlysning",
    ADD_FAVORITE: "Favorit",
    ADDING_TITLE_TEXT_1: "Vi har lagt in totalt",
    ADDING_TITLE_TEXT_2: "% av alla titlar i databasen.",
    ADMIN_LEAD: "Här kan du som är Admin lägga in och redigera data i databasen.",
    ADMIN_INFO: "När all annan info är klar - Ladda upp bilden. Så blir det lätt att få översikt över vilka objekt som behöver mer content. För frågor och instruktioner - maila Super-Admin.",
    ADMIN_INFO_2: "För frågor, support och förslag på kommande funktioner - maila Super-Admin.",
    ADMIN_ISSUE_LEAD: "Här kan du redigera information om publikationen och lägga till en bild (framsida).",
    ADMIN_ISSUE_TEXT: "Hämta ner bild från titelns cover gallery på Grand Comics Database (large). Ladda sedan upp den. Här kan du även ange om publikationen ingår i Marvelklubben eller inte, samt ange numrering.",
    ADMIN_PUBLISHER_LEAD: "Här kan du redigera information om förlaget och lägga till en bild (logotyp).",
    ADMIN_TITLE_LEAD: "Här kan du redigera information om titeln. Du kan lägga till en bild (logotyp), samt även publikationer. Publikationer kan läggas till en och en, eller i bulk.",
    ALERT_HOME_NAME_INFO: "Under inställningar kan du redigera din personliga information och lägga in en profilbild. Här väljer du också om din personliga profilsida ska vara publik.",
    ALERT_HOME_IS_PUBLIC_INFO: "Under inställningar kan du ställa in om din personliga profilsida ska vara publik.",
    ALLOW_LOCATION_ACCESS_PROMPT: "Genom att markera detta alternativ godkänner du att vi använder din platsinformation. Vi följer strikta integritetsprinciper och använder din platsdata endast för detta ändamål. Din platsinformation kommer inte att sparas eller användas för något annat syfte utan ditt uttryckliga samtycke. Du kan när som helst ändra dessa inställningar. Vi värnar om din integritet och tar skyddet av din personliga data på stort allvar.",
    ALWAYS_AVAILABLE: "Perfekt att använda när du är ute på fältet och letar tidningar.",
    AUTO_GENERATE_ISSUES_FOR: "Lägg till publikationer för",
    AUTO_GENERATE_ISSUES_INFO: "Genererar automatiskt publikationer för varje år. Baserat på startår till slutår och totala antalet publikationer. Välj förlag ovanför.",
    AUTO_GENERATE_ISSUES_CHOSEN_PUBLISHER: "Du har valt förlaget ",
    AUTO_GENERATE_ISSUES_NO_CHOICE: "Du har inte valt något förlag än!",
    CHANGE_PASSWORD_SEND_INFO: "Vi skickar information för att bekräfta återställning av lösenord.",
    CHANGE_PASSWORD_INFO: "OBS! Lösenordet ändras direkt - vi skickar ingen information för att bekräfta återställning av lösenord.",
    CHANGE_EMAIL_SEND_INFO: "Vi skickar information för att bekräfta ändring av e-postadress.",
    CHOOSE_PUBLISHER_FOR_ISSUE: "Välj förlag för dina publikationer",
    COLLECT_TITLE_START: "Börja samla på titeln",
    COLLECT_TITLE_STOP: "Sluta samla på titeln",
    COLLECT_TITLE_STOP_REMOVE: "Du måste tömma samlingen på publikationer innan du kan sluta samla på den här titeln.",
    COLLECT_ISSUE_START: "Lägg till",
    COLLECT_ISSUE_START_2: "i samlingen.",
    COLLECT_ISSUE_STOP: "Ta bort",
    COLLECT_ISSUE_STOP_2: "från samlingen.",
    COLLECTING_ADD_ALL: "Lägg till alla",
    COLLECTING_REMOVE_ALL: "Töm samlingen",
    COLLECTING_TITLE_100: "Grattis! Du har samlat 100% av denna titel.",
    COLLECTING_TITLE_TEXT_1: "Du har samlat",
    COLLECTING_TITLE_TEXT_2: "% av denna titel.",
    COLLECTING_CHECK_GRADING_STATUS_NO_ISSUES: "Du har inte lagt in några publikationer i samlingen.",
    CONSENT: "Svenska Marvelsamlare är måna om att skydda dina personliga uppgifter. När du loggar in, eller registrerar dig, bekräftar och godkänner du att vi endast använder denna information, och eventuella cookies, för att administrera ditt konto och tillhandahålla de tjänster du förväntar dig av oss.",
    DELETE_ALL_ISSUES_INFO: "Tar bort alla publikationer för denna titel.",
    DELETE_ALL_ISSUES_FOR: "Ta bort alla publikationer för",
    DO_YOU_COLLECT: "Samlar du på svenska marveltidningar?",
    FILTER_NUMBER_TITLE_OR_YEAR: "Filtrera på nummer, titel eller årtal",
    FILTER_TITLE_OR_YEAR: "Filtrera på titel eller årtal",
    FILTER_TITLE_PUBLISHER_YEAR_OR_SOURCE: "Filtrera på titel, förlag, årtal eller källmaterial",
    FILTER_NAME: "Filtrera på namn",
    FILTER_PUBLISHER_NAME: "Filtrera på förlagets namn",
    FOOTER_INFO_TEXT_1: "Denna sajt innehåller bilder och information vars copyright ägs av",
    FOOTER_INFO_TEXT_2: "och används i enlighet med Fair use doctrine of the United States.",
    FOOTER_INFO_TEXT_3: "Information har också hämtats från följande källor:",
    GENERATE_ISSUES: "Lägg till publikationer",
    GENERATING_ISSUES: "Lägger till publikationer",
    GRADE_IS_NOT_VALUED: "Vissa publikationer saknar värden.",
    GRADE_IS_VALUED_LEAD: "Här kan du markera att alla publikationer på den här titeln har fått rätt värden.",
    GRADE_TEXT_2: "Ange en skickgradering för varje exemplar du har. På så sätt kan du ha mer än ett ex av varje publikation i din samling. Mer information om skickgradering, och mer exakt värdering, hittar du hos",
    GRADE_TEXT_3: "Seriekatalogen",
    GRADE_TEXT_4: "Använd gärna meddelandefunktionen för att meddela Admin om värden behöver uppdateras.",
    GRADE_TITLE_IS_VALUED: "Alla publikationer har fått rätt värden.",
    GRADE_ISSUE_IS_VALUED_TEXT: "Publikationen har fått grundvärden.",
    GRADE_ADD_VALUE_TEXT: "Grundvärden för denna publikation saknas. Tryck på knappen för att lägga till.",
    GRADE_VALUED: "Har värden",
    GRADE_NOT_VALUED: "Saknar värden",
    INFO_TEXT_1: "Här hittar du information om aktuella releaser och kommande funktionalitet.",
    LATEST_ISSUES: "Senast inlagda publikationer:",
    LATEST_TITLES: "Senast inlagda titlar:",
    MAKE_PUBLIC: "Gör din profilsida och information publik",
    MANAGE_YOUR_COLLECTION: "Övervaka och administrera din samling.",
    MARVELKLUBBEN_LEAD: "En överblick över alla publikationer som ingick i Marvelklubben.",
    MARVELKLUBBEN_TEXT_1: "Du måste lägga börja samla på titeln för att kunna lägga till publikationen i din samling.",
    MARVELKLUBBEN_TEXT_2: "Mer information om Marvelklubben hittar du på",
    MESSAGE_WAS_SENT: "Meddelandet skickades",
    MESSAGE_LINK: "Länk till bifogat objekt",
    MESSAGE_LINK_SENDER: "Länk till anmälare",
    MESSAGES_ADMIN_TEXT_1: "Här kan du hantera meddelanden.",
    MESSAGES_ADMIN_TEXT_2: "Du kan bland annat sända ut globala meddelanden som visas för alla användare. Samt administrera inkomna meddelanden.",
    NEW_TITLES: "Nya titlar och funktioner läggs till regelbundet.",
    NO_DATA_AVAILABLE: "Det finns inget att visa!",
    NO_USER_AVAILABLE: "Denna användare har ingen publik profil!",
    REMOVE_ALL_VALUATION_VALUES_FOR_USER: "Ta bort alla sparade värderingar för användaren",
    REMOVE_ISSUE_WANTED: "Ta bort efterlysning",
    REMOVE_FAVORITE: "Ta bort favorit",
    SECTIONS: {
        GRADES: {},
        ISSUES: {},
        MESSAGES: {},
        PUBLISHERS: {},
        TITLES: {},
        USERS: {}
    },
    SETTINGS_CREDENTIALS: "Ändra din e-postadress (användarnamn) eller lösenord här.",
    SETTINGS_LEAD: "Här kan du ställa in profilbild, ändra din information samt ändra dina inloggningsuppgifter.",
    SETTINGS_INFO: "För frågor - kontakta Super-Admin.",
    SHOWING_LATEST_PUBLISHERS: "Visar de senast inlagda förlagen från databasen.",
    SHOWING_LATEST_MESSAGES: "Visar senast inkomna eller skickade meddelanden, samt eventuella globala meddelanden från Admin.",
    SHOWING: "Visar",
    SHOWING_OF: "av",
    SHOWING_LATEST_TITLES: "Visar de senast inlagda titlarna från databasen. För att lägga till en ny titel:",
    SHOWING_LATEST_TITLES_STEP_1: "Skapa titel",
    SHOWING_LATEST_TITLES_STEP_2: "Lägg till publikationer",
    SHOWING_LATEST_TITLES_STEP_3: "För varje publikation - lägg till skickgradering",
    SHOWING_LATEST_TITLES_STEP_4: "På titeln - populera alla publikationer med grundvärden för skickgradering",
    SHOWING_LATEST_USERS: "Visar de senast uppdaterade användarna från databasen.",
    SIGN_UP_SUCCESS_TEXT: "Visar de senast inlagda förlagen från databasen.",
    SOURCE_EXAMPLE: "EXEMPEL: Titel #1 (år) - https://comics.org/issue/12345; Amazing Spiderman #225 (1998) - https://comics.org/issue/23543254",
    STATUS_404_ROUTE: "Hittade tyvärr ingen route för",
    TOTAL_ISSUE_COUNT: "Totalt antal inlagda publikationer:",
    TOTAL_PUBLISHED: "Totalt gavs det ut",
    TOTAL_PUBLISHED_PUBLICATION: "publikation som kan vara intressant för marvelsamlare.",
    TOTAL_PUBLISHED_PUBLICATIONS: "publikationer som kan vara intressanta för marvelsamlare.",
    TOTAL_TITLE_COUNT: "Totalt antal inlagda titlar:",
    UPDATE_DEFAULT_VALUES: "Populera publikationer med grundläggande värden - OBS! alla publikationer måste ha fått sin skickgradering",
    USERS_COUNT_TEXT_1: "Totalt finns det ",
    USERS_COUNT_TEXT_2: "användare.",
    UTILS: "Speciella funktioner för förbättrade användarupplevelser.",
    UTILS_UPDATE_RELEASE_DATE: "Uppdatera datum för senaste release till dagens datum.",
    VALUATION_CALCULATE_MESSAGE_1: "Ingen värdeförändring - behöver inte spara ny värdering.",
    VALUATION_CALCULATE_MESSAGE_2: "Inga värderingar funna - sparar ny värdering.",
    VALUATION_CALCULATE_MESSAGE_3: "För att vi ska kunna beräkna en värdering måste du lägga in skickgraderingar på dina publikationer.",
    WELCOME_TEXT_1: "Hej",
    WELCOME_TEXT_2: "och välkommen till Svenska Marvelsamlare!"
}

export const PANES = {
    TITLES: {
        NAME: "Mina titlar",
        LONG_NAME: "Kontrollpanelen - Mina titlar",
        SHORT_NAME: "Titlar",
        COLLECTING_CHECK_GRADING_STATUS_OPEN_1: "Beräknar värdet och kontrollerar om något exemplar av",
        COLLECTING_CHECK_GRADING_STATUS_OPEN_2: "behöver skickgradering.",
        GRADE_MISSING: "Det verkar som att några publikationer saknar skickgradering.",
        GRADE_FOUND: "Alla publikationer har skickgradering.",
        COLLECTING_VALUE_1: "Det sammanlagda värdet av denna titel är: ",
    },
    ISSUES: {
        NAME: "Mina publikationer",
        LONG_NAME: "Kontrollpanelen - Mina publikationer",
        SHORT_NAME: "Publikationer"
    },
    OVERVIEW: {
        NAME: "Översikt",
        LONG_NAME: "Kontrollpanelen - Översikt",
        COLLECTING_TITLES_1: "Du samlar på",
        COLLECTING_TITLES_2: "av totalt",
        COLLECTING_TITLES_3: "inlagda titlar.",
        COLLECTING_VALUE_1: "Det sammanlagda värdet av din samling är: ",
        COLLECTING_VALUE_2: "Vilket är en ökning med",
        COLLECTING_VALUE_3: "Vilket är en minskning med",
        COLLECTING_VALUE_4: "sedan senast sparade värdering",
        COLLECTING_VALUE_6: "Ingen värdeförändring.",
        COLLECTING_VALUE_7: "Det finns inga sparade värderingar. Gå till värderingssidan för att räkna ut ett nytt värde på din samling.",
        COLLECTING_ISSUES_1: "Totalt ingår",
        COLLECTING_ISSUES_2: "publikationer i din samling, som är till",
        COLLECTING_ISSUES_3: "komplett.",
        COLLECTING_MARVELKLUBBEN_1: "Du har",
        COLLECTING_MARVELKLUBBEN_2: "publikationer i din Marvelklubben-samling. Den är till",
        GRADE: "Gradering",
        COLLECTING_ISSUES_GRADE_1: "Publikationerna i din samling har en snittgradering på",
        SEE_PROFILE_FOR_MORE_WANTED: "Se alla efterlysningar på din profilsida",
        SEE_PROFILE_FOR_MORE_NEEDS_GRADING: "Se fler publikationer på din profilsida",
        SEE_PROFILE_FOR_MORE_FAVORITES: "Se fler favoriter på din profilsida",
        SEE_PROFILE_FOR_MORE_FAVORITE_TITLES: "Se fler favorittitlar på din profilsida",
    },
    COLLECTIONS: {
        NAME: "Samlingar",
        LONG_NAME: "Kontrollpanelen - Samlingar",
        COLLECTING: "Samlar på",
        TITLES: "titlar",
        COMPLETE: "% komplett",

    },
    VALUATION: {
        NAME: "Värdering",
        LONG_NAME: "Kontrollpanelen - Värdering",
        LEAD: "Här visas de senaste värderingarna som sparats i databasen. Vi visar max 20 st. För att vi ska kunna beräkna en värdering måste du lägga in skickgraderingar på dina publikationer.",
        COLLECTING_VALUE_1: "Det sammanlagda värdet av din samling är: ",
    },
    MAP: {
        NAME: "Karta",
        LONG_NAME: "Kontrollpanelen - Karta",
        LEAD_1: "Om du har valt att låta Svenska Marvelsamlare använda din position kan du här enkelt leta efter loppisar, second hand-butiker eller serietidningsaffärer nära dig.",
        LEAD_2: "Du kan även ange platsinformation manuellt.",
        FLEA_MARKETS: "Loppmarknader",
        SECOND_HAND_SHOPS: "Second hand-butiker",
        COMIC_BOOK_STORES: "Serietidningsaffärer",
        WALKING: "Promenad",
        DRIVING: "Köra bil",
        TRAVEL_MODES: "Färdsätt",
        NEAREST_DESTINATIONS: "nära dig:",
        ALTERNATIVE_ROUTES: "Alternativa vägar",
        SEARCH_FOR_NEAREST: "Sök",
        LOCATION: "Plats",
        YOUR_CURRENT_LOCATION: "Din nuvarande plats:",
        YOUR_SELECTED_ORIGIN_LOCATION: "Din valda plats:",
        NO_SELECTED_ORIGIN_LOCATION: "Du har inte valt någon annan plats än.",
        CHOSE_LOCATION: "Välj plats:",
        CHOSE_OTHER_LOCATION: "Välj en annan plats:"
    }
}
